---

- name: Install source postgresql
  ansible.builtin.shell:
    cmd: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: Add key postgresql
  ansible.builtin.shell:
    cmd: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

- name: Install packages
  ansible.builtin.apt:
    name:
      - postgresql-{{postgresql_version}}
      - libpq-dev
      - python3-psycopg2
    state: present

